sistemaInventarioWeb/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaInventarioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_marca { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}

sistemaInventarioWeb/Controllers/MarcasController.cs
using sistemaInventarioWeb.Models;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace sistemaInventarioWeb.Controllers
{
    public class MarcasController : Controller
    {
        private ventasdbEntities db = new ventasdbEntities();
        //GET
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Marca marca)
        {
            db.Marca.Add(marca);
            db.SaveChanges();
            return View();
        }
        public ActionResult Index()
        {
            var listaMarcas = db.Marca.ToList();
            return View(listaMarcas);
        }
        //variable int? significa que puede ser nulo 
        public ActionResult Edit(int? id)
        {
            if(id != null)
            {
                var marca = db.Marca.Find(id);
                if(marca != null)
                    return View(marca);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(Marca marca)
        {
            //editamos con los datos enviados
            db.Entry(marca).State = EntityState.Modified;
            //guardo los cambios en la db
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var marca = db.Marca.Find(id);
                if (marca != null)
                    return View(marca);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var marca = db.Marca.Find(id);
            if(marca != null)
            {
                //quitar el registro de la marca
                db.Marca.Remove(marca);
                //guardar los cambios
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

sistemaInventarioWeb/Views/Marcas/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h1>Crear Marca</h1>
<hr />
<form method="post">
    <div class="form-group">
        <label>Nombre Marca</label>
        <input type="text" class="form-control" name="nombre" id="nombre">
    </div>
    <a href="@Url.Action("Index","Marcas")" class="btn btn-default">Volver a Marcas</a>
    <button type="submit" class="btn btn-primary" id="btnEnviar" >Guardar</button>
</form>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    //Difernetes formas de llamar según librería
    //documet.getElementById('btnEnviar')//aceptada por cualquier librería de javascript
    //$('#btnEnviar')//aceptado siempre y cuando se utilice jquery 
    $('#btnEnviar').click(function (e) {
        let marca = document.getElementById('nombre').value;
        if (marca == '') {
            alert('Debe ingresar una marca');
            e.preventDefault();
        }
    });
    //TODO: Revisar porque se envia el formulario
    //function validar() {
    //    //captura el valor escrito en el input y se asigna a la variable marca
    //    let marca = document.getElementById('nombre').value;
    //    if (marca == '') {
    //        alert('Debe ingresar una marca');
    //    }
    //}
</script>

sistemaInventarioWeb/Views/Marcas/Delete.cshtml
@model sistemaInventarioWeb.Models.Marca
@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar marca</h2>

<h3>¿Está seguro que desea eliminar la marca?</h3>

<form method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="@Model.id_marca" />
        <label class="control-label">Nombre Marca:</label>
        <label>@Model.nombre</label>
    </div>
    <a href="@Url.Action("Index","Marcas")" class="btn btn-default">Volver a marcas</a>
    <button class="btn btn-danger" type="submit">Eliminar</button>
</form>

sistemaInventarioWeb/Views/Marcas/Edit.cshtml
@model sistemaInventarioWeb.Models.Marca
@{
    ViewBag.Title = "Edit";
}

<h2>Editar Marca</h2>

<form method="post">
    <div class="form-group">
        <input type="hidden" name="id_marca" value="@Model.id_marca" />
        <label class="control-label">Nombre Marca</label>
        <input type="text" name="nombre" value="@Model.nombre" class="form-control" />
    </div>
    <a href="@Url.Action("Index","Marcas")" class="btn btn-default">Volver a marcas</a>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

sistemaInventarioWeb/Views/Marcas/Index.cshtml
@model IEnumerable<sistemaInventarioWeb.Models.Marca>
@{
    ViewBag.Title = "Index";
}

<h2>Lista con todas las marcas</h2>

<div class="col-12">
    <table class="table table-hover table-bordered">
        <thead>
            <tr class="bg-success">
                <th>Id Marca</th>
                <th>Nombre</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.id_marca</td>
                    <td>@item.nombre</td>
                    <td>
                        <a href="@Url.Action("Edit","Marcas",new { id = item.id_marca })">Editar</a> |
                        <a href="@Url.Action("Delete","Marcas",new { id = item.id_marca })">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>